name : Main WF
on : push
jobs:
    main:
        runs-on : ubuntu-latest
        steps:
            - name : get code
              uses : actions/checkout@v3
            - name: list-files
              run : echo "ls"
            - name : call-remote
              uses: ./.github/workflows/reusable.yml
              with :
                msg : hello from main