#https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
#Add commit message [skip ci] to skip workflow 
name : Workflow Status
on : 
    workflow_call:
        inputs : 
            msg:
                description: This is from reusable wf
                required: false
                default : Hello
                type : string
        
jobs: 
    remote-wf:
        runs-on : ubuntu-latest
        steps:
            - name : input-from-main-wf
              run  : echo " ${{inputs.msg}}"